version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
  test:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: ./mvnw test

workflows:
  maven_test:
    jobs:
      - test # checkout, build, test, and upload test results